-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 18, 2020 at 11:19 AM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `smartsearch`
--

-- --------------------------------------------------------

--
-- Table structure for table `book`
--

CREATE TABLE `book` (
  `id_ss` int(20) NOT NULL,
  `StoreName` varchar(100) NOT NULL,
  `Bname` varchar(100) NOT NULL,
  `author` varchar(100) NOT NULL,
  `Btype` varchar(100) NOT NULL,
  `price` int(20) NOT NULL,
  `publication_date` date NOT NULL,
  `highlight` text NOT NULL,
  `total` int(100) NOT NULL,
  `pic` blob NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `book`
--

INSERT INTO `book` (`id_ss`, `StoreName`, `Bname`, `author`, `Btype`, `price`, `publication_date`, `highlight`, `total`, `pic`) VALUES
(0, 'สมใจ', 'one upon a time', 'samuel', 'novel', 350, '2014-04-17', 'เรื่องราวระหว่างสาวนักเขียนนิยายสายซึนที่ไม่ยอมหัวปักหัวปำกับความรักง่ายๆ กับท่านประธานสายเทคแคร์แบบจัดเต็มที่ทำทุกวิถีทางเพื่อเอาชนะใจเธอ', 120, ''),
(1, 'Fahsai', 'herry potter', 'J.K. Rowling', 'children\'s litetature', 690, '1997-11-07', 'This article is about the series of novels. For other uses, including related topics and derivative works, see Harry Potter (disambiguation). For the character in the series, see Harry Potter (character). For the film adaptations, see Harry Potter (film series). For the franchise as a whole, see Wizarding World.', 69, ''),
(2, 'Monday', 'hello word', 'Hannah fry', 'knowledge', 527, '2017-02-10', '\"Hello, World\" หนังสือวิทยาศาสตร์ และธรรมชาติเบื้องต้นสำหรับเด็ก หนังสือชุดนี้จะพูดถึง ร่างกายของเรา, ระบบสุริยะ, สภาพอากาศ, แมลง, นก และไดโนเสาร์ เด็กๆ อ่านแล้วมีความรู้ความเข้าใจเกี่ยวกับเรื่องดังกว่ามากขึ้น หรือผู้ปกครองใช้เป็นสื่อในการอธิบายเรื่องเหล่านี้ให้กับลูกๆ เพื่อให้เกิดความเข้าใจ เสริมสร้างความรู้รอบตัวให้กับเด็ก ', 100, ''),
(3, 'Catty', 'Harry Potter and the Philosopher\'s Stone', 'J. K. Rowling', 'Novel', 389, '1997-06-26', 'When mysterious letters start arriving on his doorstep, Harry Potter has never heard of Hogwarts School of Witchcraft and Wizardry. They are swiftly confiscated by his aunt and uncle.Then, on Harry’s eleventh birthday, a strange man bursts in with some important news: Harry Potter is a wizard and has been awarded a place to study at Hogwarts. And so the first of the Harry Potter adventures is set to begin.', 78, ''),
(4, 'Daddy', 'Harry Potter and the Chamber of Secrets', 'J. K. Rowling', 'Novel', 359, '1998-07-02', 'Harry Potter\'s summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors – and then the attacks start. Students are found as though turned to stone … Dobby\'s sinister predictions seem to be coming true.', 96, ''),
(5, 'Elfie', 'Harry Potter and the Prisoner of Azkaban', 'J. K. Rowling', 'Novel', 300, '1999-07-08', 'For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.', 88, ''),
(6, 'Fatty', 'Harry Potter and the Goblet of Fire', 'J. K. Rowling', 'Novel', 259, '2000-07-08', 'Harry Potter wants to get away from the pernicious Dursleys and go to the International Quidditch Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event involving two other rival schools of magic, and a competition that hasn\'t happened for a hundred years. He wants to be a normal, fourteen-year-old wizard. Unfortunately for Harry Potter, he\'s not normal - even by wizarding standards. And in this case, different can be deadly.', 28, ''),
(7, 'Goroko', 'Harry Potter and the Order of the Phoenix', 'J. K. Rowling', 'Novel', 299, '2003-06-21', 'Whisk your child back to Hogwarts for Harry\'s fifth year at wizard school, filled with run-ins with the new Defense Against the Dark Arts teacher, a disgruntled house-elf, and even tougher end-of-term exams. Add this to the rift Lord Voldemort\'s rise has opened in the wizarding world -- between those who believe the truth about his return and those who prefer to believe it\'s all madness and lies -- and you\'ve got another (even longer!) adventure that\'s sure to cast a reading spell over your child.', 8, ''),
(8, 'Hallow', 'Harry Potter and the Half-Blood Prince', 'J. K. Rowling', 'Novel', 239, '2005-07-16', 'The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses.', 19, ''),
(9, 'Icy', 'Harry Potter and the Deathly Hallows', 'J. K. Rowling', 'Novel', 259, '2007-07-21', 'Harry Potter is leaving Privet Drive for the last time. But as he climbs into the sidecar of Hagrids motorbike and they take to the skies, he knows Lord Voldemort and the Death Eaters will not be far behind.', 85, ''),
(10, 'Jack', 'Harry Potter and the Cursed Child - Parts One and Two', 'J. K. Rowling', 'Novel', 259, '2016-07-31', 'It was always difficult being Harry Potter and it isn’t much easier now that he is an overworked employee of the Ministry of Magic, a husband, and father of three school-age children.', 293, ''),
(11, 'King', 'The 7 Habits Of Highly Effective People', 'Stephen Covey', 'Self-help book', 189, '1989-08-15', 'In The 7 Habits of Highly Effective People, author Stephen R. Covey presents a holistic, integrated, principle-centered approach for solving personal and professional problems. With penetrating insights and pointed anecdotes, Covey reveals a step-by-step pathway for living with fairness, integrity, service, and human dignity--principles that give us the security to adapt to change and the wisdom and power to take advantage of the opportunities that change creates.', 56, ''),
(12, 'Lion', 'Who Moved My Cheese?', 'Spencer Johnson', 'Self-help book', 100, '1998-09-08', 'Who Moved My Cheese? is a simple parable that reveals profound truths. It is an amusing and enlightening story of four characters who live in a \"Maze\" and look for \"Cheese\" to nourish them and make them happy.', 75, ''),
(13, 'Monkey', 'The Last Lecture', 'Jeffrey Zaslow and Randy Pausch', 'Self-help book', 209, '2008-04-08', 'A lot of professors give talks titled \'The Last Lecture\'. Professors are asked to consider their demise and to ruminate on what matters most to them: What wisdom would we impart to the world if we knew it was our last chance? If we had to vanish tomorrow, what would we want as our legacy?', 125, ''),
(14, 'Nutto', 'Get Out of Your Head: Stopping the Spiral of Toxic Thoughts', 'Jennie Allen', 'Self-help book', 159, '2020-01-28', 'The visionary behind the million-strong IF:Gathering challenges Christian women to transform their outlook and their lives by interrupting their spiraling thoughts and realizing their God-given power to think differently.', 34, ''),
(15, 'OHHO', 'The Great Gatsby', 'F.Scott Fitzgerald', 'Novel', 80, '1925-04-10', 'The Great Gatsby, F. Scott Fitzgerald’s 1925 Jazz Age novel about the impossibility of recapturing the past, was initially a failure. Today, the story of Gatsby’s doomed love for the unattainable Daisy is considered a defining novel of the 20th century. Explore a character analysis of Gatsby, plot summary, and important quotes.', 878, ''),
(16, 'Peaches', 'A Conversation Book 1: English in Everyday Life', 'Carolyn Graham', 'Text book', 131, '2006-04-28', 'A Conversation Book 1: English in Everyday Life, by Tina Kasloff Carver and Sandra D. Fotinos-Riggs, helps beginning level students to develop conversation fluency. The student-centered text and audio teach the vocabulary and life skills necessary for natural communication. Each of the ten units focuses on an essential aspect of daily life such as food, shopping, and work. Activities ranging from role plays to group surveys promise a lively class and help students achieve the language competencies needed to succeed at school and work.', 25, ''),
(17, 'Queen', 'English Grammar in Use Supplementary Exercises with Answers', 'Louise Hashemi , With  Raymond Murphy', 'Text book', 499, '2012-11-12', 'This new edition has been thoroughly updated and revised to accompany the fourth edition of English Grammar in Use. The book contains 200 varied exercises to provide students with extra practice of the grammar they have studied. This \'with answers\' version is ideal for self-study. A version without answers is available separately.', 112, ''),
(18, 'Rocky', 'English Writing ฉบับสมบูรณ์', 'ม.ล. ฐนิสา ชุมพล', 'Text book', 190, '2019-01-07', '\"English Writing ฉบับสมบูรณ์\" เล่มนี้ ผู้เขียนตั้งใจเขียนขึ้นจากประสบการณ์การสอน Academic English Writing (การเขียนเชิงวิชาการ) ให้กับนักเรียนหลายๆ เชื้อชาติ และพบว่าถึงแม้หลายคนจะใช้ภาษาอังกฤษสื่อสารได้คล่อง แต่พอต้องเขียนงานวิจัย หรือรายงานทางวิชาการ ก็จะมีปัญหาเหมือนๆ กันหมด เนื้อหาในเล่มจึงเปรียบเหมือนการศึกษาวิจัยนักศึกษาของตัวผู้เขียนเอง ที่มีระยะเวลามากกว่า 10 ปี และประมวลผลวิจัยออกมาว่า ผู้เรียนมีปัญหาจุดใดบ้าง แล้วเสนอวิธีแก้ไขปัญหาเหล่านั้นอย่างเข้าใจง่าย โดยเน้นไปที่ไวยากรณ์และตัวอย่าง เพื่อใช้ในการเขียนภาษาอังกฤษโดยเฉพาะ', 378, ''),
(19, 'Sassy', 'DKTODAY ดวงกมลสมัย CAM.GLOBAL ENGLISH 5:ACTIVITY BOOKS', 'JANE BOYLAN AND CLAIRE MEDWELL', 'Text book', 179, '2014-03-07', 'Cambridge Global English (1-6) is a six-level Primary course following the Cambridge Primary English as a Second Language Curriculum Framework developed by Cambridge English Language Assessment. Activity Book 5 provides additional practice activities to consolidate language skills and content material introduced in Learner\'s Book 5. Nine units correspond with the topics, texts and language input of Learner\'s Book 5 with each lesson of the Learner\'s Book supported by two pages in the Activity Book. Learning is reinforced through activities clearly framed within the \'I can\' objectives of the course, opportunities for personalisation and creative work and a higher level of challenge to support differentiation. Each unit in the Activity Book ends with revision and opportunity for self-assessment. CEFR Level: A2.', 865, ''),
(20, 'Tom and Jerry', 'A History of Food in 100 Recipes', 'William Sitwell', 'Cook book', 245, '2017-03-09', 'We all love to eat, and most people have a favorite ingredient or dish. But how many of us know where our much-loved recipes come from, who invented them, and how they were originally cooked? In A History of Food in 100 Recipes, culinary expert and BBC television personality William Sitwell explores the fascinating history of cuisine from the first cookbook to the first cupcake, from the invention of the sandwich to the rise of food television.', 8, ''),
(21, 'Catty', 'Harry Potter and the Chamber of Secrets', 'J. K. Rowling', 'Novel', 309, '1998-07-02', 'Harry Potter\'s summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors – and then the attacks start. Students are found as though turned to stone … Dobby\'s sinister predictions seem to be coming true.', 6, ''),
(22, 'Catty', 'Harry Potter and the Prisoner of Azkaban', 'J. K. Rowling', 'Novel', 310, '1999-07-08', 'For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.', 818, ''),
(23, 'Catty', 'Harry Potter and the Goblet of Fire', 'J. K. Rowling', 'Novel', 159, '2000-07-08', 'Harry Potter wants to get away from the pernicious Dursleys and go to the International Quidditch Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event involving two other rival schools of magic, and a competition that hasn\'t happened for a hundred years. He wants to be a normal, fourteen-year-old wizard. Unfortunately for Harry Potter, he\'s not normal - even by wizarding standards. And in this case, different can be deadly.', 8, ''),
(24, 'Catty', 'Harry Potter and the Order of the Phoenix', 'J. K. Rowling', 'Novel', 289, '2003-06-21', 'Whisk your child back to Hogwarts for Harry\'s fifth year at wizard school, filled with run-ins with the new Defense Against the Dark Arts teacher, a disgruntled house-elf, and even tougher end-of-term exams. Add this to the rift Lord Voldemort\'s rise has opened in the wizarding world -- between those who believe the truth about his return and those who prefer to believe it\'s all madness and lies -- and you\'ve got another (even longer!) adventure that\'s sure to cast a reading spell over your child.', 88, ''),
(25, 'Catty', 'Harry Potter and the Half-Blood Prince', 'J. K. Rowling', 'Novel', 209, '2005-07-16', 'The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses.', 9, ''),
(26, 'Catty', 'Harry Potter and the Deathly Hallows', 'J. K. Rowling', 'Novel', 299, '2007-07-21', 'Harry Potter is leaving Privet Drive for the last time. But as he climbs into the sidecar of Hagrids motorbike and they take to the skies, he knows Lord Voldemort and the Death Eaters will not be far behind.', 5, ''),
(27, 'Catty', 'Harry Potter and the Cursed Child - Parts One and Two', 'J. K. Rowling', 'Novel', 209, '2016-07-31', 'It was always difficult being Harry Potter and it isn’t much easier now that he is an overworked employee of the Ministry of Magic, a husband, and father of three school-age children.', 93, ''),
(28, 'Daddy', 'Harry Potter and the Philosopher\'s Stone', 'J. K. Rowling', 'Novel', 389, '1997-06-26', 'When mysterious letters start arriving on his doorstep, Harry Potter has never heard of Hogwarts School of Witchcraft and Wizardry. They are swiftly confiscated by his aunt and uncle.Then, on Harry’s eleventh birthday, a strange man bursts in with some important news: Harry Potter is a wizard and has been awarded a place to study at Hogwarts. And so the first of the Harry Potter adventures is set to begin.', 7, ''),
(29, 'Daddy', 'Harry Potter and the Prisoner of Azkaban', 'J. K. Rowling', 'Novel', 300, '1999-07-08', 'For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.', 8, ''),
(30, 'Daddy', 'Harry Potter and the Goblet of Fire', 'J. K. Rowling', 'Novel', 259, '2000-07-08', 'Harry Potter wants to get away from the pernicious Dursleys and go to the International Quidditch Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event involving two other rival schools of magic, and a competition that hasn\'t happened for a hundred years. He wants to be a normal, fourteen-year-old wizard. Unfortunately for Harry Potter, he\'s not normal - even by wizarding standards. And in this case, different can be deadly.', 28, ''),
(31, 'Daddy', 'Harry Potter and the Order of the Phoenix', 'J. K. Rowling', 'Novel', 299, '2003-06-21', 'Whisk your child back to Hogwarts for Harry\'s fifth year at wizard school, filled with run-ins with the new Defense Against the Dark Arts teacher, a disgruntled house-elf, and even tougher end-of-term exams. Add this to the rift Lord Voldemort\'s rise has opened in the wizarding world -- between those who believe the truth about his return and those who prefer to believe it\'s all madness and lies -- and you\'ve got another (even longer!) adventure that\'s sure to cast a reading spell over your child.', 8, ''),
(32, 'Daddy', 'Harry Potter and the Half-Blood Prince', 'J. K. Rowling', 'Novel', 239, '2005-07-16', 'The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses.', 9, ''),
(33, 'Daddy', 'Harry Potter and the Deathly Hallows', 'J. K. Rowling', 'Novel', 259, '2007-07-21', 'Harry Potter is leaving Privet Drive for the last time. But as he climbs into the sidecar of Hagrids motorbike and they take to the skies, he knows Lord Voldemort and the Death Eaters will not be far behind.', 5, ''),
(34, 'Daddy', 'Harry Potter and the Cursed Child - Parts One and Two', 'J. K. Rowling', 'Novel', 259, '2016-07-31', 'It was always difficult being Harry Potter and it isn’t much easier now that he is an overworked employee of the Ministry of Magic, a husband, and father of three school-age children.', 23, ''),
(35, 'Elfie', 'Harry Potter and the Philosopher\'s Stone', 'J. K. Rowling', 'Novel', 359, '1997-06-26', 'When mysterious letters start arriving on his doorstep, Harry Potter has never heard of Hogwarts School of Witchcraft and Wizardry. They are swiftly confiscated by his aunt and uncle.Then, on Harry’s eleventh birthday, a strange man bursts in with some important news: Harry Potter is a wizard and has been awarded a place to study at Hogwarts. And so the first of the Harry Potter adventures is set to begin.', 178, ''),
(36, 'Elfie', 'Harry Potter and the Chamber of Secrets', 'J. K. Rowling', 'Novel', 359, '1998-07-02', 'Harry Potter\'s summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors – and then the attacks start. Students are found as though turned to stone … Dobby\'s sinister predictions seem to be coming true.', 96, ''),
(37, 'Elfie', 'Harry Potter and the Goblet of Fire', 'J. K. Rowling', 'Novel', 259, '2000-07-08', 'Harry Potter wants to get away from the pernicious Dursleys and go to the International Quidditch Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event involving two other rival schools of magic, and a competition that hasn\'t happened for a hundred years. He wants to be a normal, fourteen-year-old wizard. Unfortunately for Harry Potter, he\'s not normal - even by wizarding standards. And in this case, different can be deadly.', 28, ''),
(38, 'Elfie', 'Harry Potter and the Order of the Phoenix', 'J. K. Rowling', 'Novel', 299, '2003-06-21', 'Whisk your child back to Hogwarts for Harry\'s fifth year at wizard school, filled with run-ins with the new Defense Against the Dark Arts teacher, a disgruntled house-elf, and even tougher end-of-term exams. Add this to the rift Lord Voldemort\'s rise has opened in the wizarding world -- between those who believe the truth about his return and those who prefer to believe it\'s all madness and lies -- and you\'ve got another (even longer!) adventure that\'s sure to cast a reading spell over your child.', 8, ''),
(39, 'Elfie', 'Harry Potter and the Half-Blood Prince', 'J. K. Rowling', 'Novel', 239, '2005-07-16', 'The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses.', 19, ''),
(40, 'Elfie', 'Harry Potter and the Deathly Hallows', 'J. K. Rowling', 'Novel', 259, '2007-07-21', 'Harry Potter is leaving Privet Drive for the last time. But as he climbs into the sidecar of Hagrids motorbike and they take to the skies, he knows Lord Voldemort and the Death Eaters will not be far behind.', 5, ''),
(41, 'Elfie', 'Harry Potter and the Cursed Child - Parts One and Two', 'J. K. Rowling', 'Novel', 259, '2016-07-31', 'It was always difficult being Harry Potter and it isn’t much easier now that he is an overworked employee of the Ministry of Magic, a husband, and father of three school-age children.', 29, ''),
(42, 'Fatty', 'Harry Potter and the Philosopher\'s Stone', 'J. K. Rowling', 'Novel', 389, '1997-06-26', 'When mysterious letters start arriving on his doorstep, Harry Potter has never heard of Hogwarts School of Witchcraft and Wizardry. They are swiftly confiscated by his aunt and uncle.Then, on Harry’s eleventh birthday, a strange man bursts in with some important news: Harry Potter is a wizard and has been awarded a place to study at Hogwarts. And so the first of the Harry Potter adventures is set to begin.', 78, ''),
(43, 'Fatty', 'Harry Potter and the Chamber of Secrets', 'J. K. Rowling', 'Novel', 359, '1998-07-02', 'Harry Potter\'s summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors – and then the attacks start. Students are found as though turned to stone … Dobby\'s sinister predictions seem to be coming true.', 96, ''),
(44, 'Fatty', 'Harry Potter and the Prisoner of Azkaban', 'J. K. Rowling', 'Novel', 300, '1999-07-08', 'For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.', 88, ''),
(45, 'Fatty', 'Harry Potter and the Order of the Phoenix', 'J. K. Rowling', 'Novel', 299, '2003-06-21', 'Whisk your child back to Hogwarts for Harry\'s fifth year at wizard school, filled with run-ins with the new Defense Against the Dark Arts teacher, a disgruntled house-elf, and even tougher end-of-term exams. Add this to the rift Lord Voldemort\'s rise has opened in the wizarding world -- between those who believe the truth about his return and those who prefer to believe it\'s all madness and lies -- and you\'ve got another (even longer!) adventure that\'s sure to cast a reading spell over your child.', 8, ''),
(46, 'Fatty', 'Harry Potter and the Half-Blood Prince', 'J. K. Rowling', 'Novel', 239, '2005-07-16', 'The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses.', 19, ''),
(47, 'Fatty', 'Harry Potter and the Deathly Hallows', 'J. K. Rowling', 'Novel', 259, '2007-07-21', 'Harry Potter is leaving Privet Drive for the last time. But as he climbs into the sidecar of Hagrids motorbike and they take to the skies, he knows Lord Voldemort and the Death Eaters will not be far behind.', 85, ''),
(48, 'Fatty', 'Harry Potter and the Cursed Child - Parts One and Two', 'J. K. Rowling', 'Novel', 259, '2016-07-31', 'It was always difficult being Harry Potter and it isn’t much easier now that he is an overworked employee of the Ministry of Magic, a husband, and father of three school-age children.', 293, ''),
(49, 'Goroko', 'Harry Potter and the Philosopher\'s Stone', 'J. K. Rowling', 'Novel', 399, '1997-06-26', 'When mysterious letters start arriving on his doorstep, Harry Potter has never heard of Hogwarts School of Witchcraft and Wizardry. They are swiftly confiscated by his aunt and uncle.Then, on Harry’s eleventh birthday, a strange man bursts in with some important news: Harry Potter is a wizard and has been awarded a place to study at Hogwarts. And so the first of the Harry Potter adventures is set to begin.', 78, ''),
(50, 'Goroko', 'Harry Potter and the Chamber of Secrets', 'J. K. Rowling', 'Novel', 359, '1998-07-02', 'Harry Potter\'s summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors – and then the attacks start. Students are found as though turned to stone … Dobby\'s sinister predictions seem to be coming true.', 96, ''),
(51, 'CelestialComic', 'เรไร ', 'เรไร สุวีรานนท์', 'Comic Book', 120, '1997-12-08', 'เรไร สุวีรานนท์ เด็กหญิงอายุ 7 ปี เริ่มต้นจดบันทึกประจำวันลงสมุด และโพสต์ลงใน \"เรไรรายวัน\" ตั้งแต่กลางปี 2558 เพจของเธอได้รับความนิยมอย่างสูง จนกระทั่งมียอดไลค์กว่าแปดหมื่นภายในเวลาเพียงหกเดือน การเป็นที่รู้จักอย่างกว้างขวางในโลกออนไลน์ ทำให้มีสื่อมาสัมภาษณ์ และรายงานเรื่องราวของเธอแล้วมากมาย', 50, ''),
(52, 'DarkStore', 'ศิลปะกรุงธนบุรีฉบับพิเศษ', 'ประภัสสร์ ชูวิเชียร', 'history', 250, '2019-08-30', 'ย้อนเวลากลับไปก่อนหน้านั้น 15 ปี กรุงธนบุรีสถาปนาขึ้นภายใต้ภาวะสงคราม สมเด็จพระเจ้าตากสินรวบรวมบ้านเมืองและผู้คนสร้างเมืองขึ้นใหม่ ในพื้นที่เมืองธนบุรี-บางกอกเดิม หลักฐานมากมายระบุว่าพื้นที่เมืองธนบุรี-บางกอก มีผู้คนอยู่อย่างหนาแน่นมาก่อนที่สมเด็จพระเจ้าตากสินจะสถาปนากรุงธนบุรี\r\nดังปรากฏวัดต่างๆ ในพื้นที่ที่มีร่องรอยศิลปะสมัยอยุธยา ซึ่งวัดเหล่านี้ได้ถูกปฏิสังขรณ์อยู่เรื่อยๆ เนื่องจากวัดเป็นพื้นที่ใช้งานของผู้คนและชุมชนจึงต้องมีการบูรณะเพื่อใช้สอยอยู่เสมอ\r\n\r\nดังนั้น ในช่วง 15 ปีของสมัยธนบุรี การซ่อม ปรับปรุง วัด จึงน่าเป็นงานช่างสมัยธนบุรีนั่นเอง', 70, ''),
(53, 'DarkStore', 'เมื่อสยามพลิกฝัน', 'ธงชัย วินิจจะกูล', 'history', 170, '1986-05-22', 'ที่สยามเกิดการปะทะปรับแปรในด้านต่างๆ โดยหยิบยกเอาเรื่องเล่าฝังหัวคนไทยมาพลิกมุมอธิบายใหม่', 99, ''),
(54, 'GoldSoul', 'มองตะเกียบเห็นป่าไผ่', 'นิธิพันธ์ วิประวิทย์', 'history', 250, '1988-05-25', 'จะพาคุณเดินทางหวนสู่อดีต ย้อนกลับมายังปัจจุบัน ผ่านเรื่องราวของบุคคล ผ่านรากแห่งวัฒนธรรม ผ่านภูมิปัญญาของผู้คน และผ่านยุคอารยธรรมอันรุ่งเรืองยาวนานหลายพันปีของชาวจีน', 35, ''),
(55, 'GoldSoul', 'ตำนานเทพเจ้าอียิปต์', 'ณัฐพล เดชขจร', 'history', 295, '1998-11-10', '\"อียิปต์โบราณ\" หนึ่งในอารยธรรมที่ยิ่งใหญ่และลึกลับน่าพิศวงที่สุดในโลก ร่องรอยอารยธรรมที่ยังคงหลงเหลือ ทั้งหมู่มหาพีระมิด การทำมัมมี่ หรือแม้แต่สุสานลับใต้ผืนทราย ล้วนทำให้คนรุ่นหลังต้องตื่นตะลึง สิ่งอัศจรรย์เหล่านี้เกิดขึ้น จากศรัทธาอันแรงกล้าที่มีต่อเทพเจ้า ความเชื่อในโลกหลังความตาย และการฟื้นคืนชีพ ตำนานแห่งเทพเจ้า รวมถึงความเชื่อของชาวอียิปต์โบราณ จึงกลายเป็นสิ่งที่คนทั่วโลกสนใจใคร่รู้ แต่น้อยคนนักที่จะได้รับคำตอบจากผู้รู้จริง ด้วยการค้นคว้าแบบเจาะลึก และครอบคลุมของผู้เขียนซึ่งคร่ำหวอดในวงการอียิปต์วิทยา \"ตำนานเทพเจ้าอียิปต์\" เล่มนี้ จึงเปรียบเสมือนยานเวลาที่จะพานักอ่านท่องไปยังดินแดนของเหล่าเทพเจ้า ผู้ทรงฤทธานุภาพในยุคสมัยของชาวไอยคุปต์ แบบ \"รู้ลึก-รู้จริง\" จนผู้อ่านจะต้องทึ่ง!', 15, ''),
(56, 'GoldSoul', 'ตำนานเทพเจ้ากรีก', 'ณัฐพล เดชขจร', 'history', 295, '1998-12-26', '\"กรีกโบราณ\" หนึ่งในอารยธรรมที่ยิ่งใหญ่และลึกลับน่าพิศวงที่สุดในโลก ร่องรอยอารยธรรมที่ยังคงหลงเหลือ ทั้งหมู่มหาพีระมิด การทำมัมมี่ หรือแม้แต่สุสานลับใต้ผืนทราย ล้วนทำให้คนรุ่นหลังต้องตื่นตะลึง สิ่งอัศจรรย์เหล่านี้เกิดขึ้น ', 55, ''),
(57, 'GoldSoul', 'ตำนานเทพเจ้าโรมัน', 'ณัฐพล เดชขจร', 'history', 295, '1997-01-22', '\"กรีกโรมัน\" หนึ่งในอารยธรรมที่ยิ่งใหญ่และลึกลับน่าพิศวงที่สุดในโลก ร่องรอยอารยธรรมที่ยังคงหลงเหลือ ทั้งหมู่มหาพีระมิด การทำมัมมี่ หรือแม้แต่สุสานลับใต้ผืนทราย ล้วนทำให้คนรุ่นหลังต้องตื่นตะลึง สิ่งอัศจรรย์เหล่านี้เกิดขึ้น ', 45, ''),
(58, 'GoldSoul', 'เจ้าจอมสยาม', 'เวนิสา เสนีวงศ์ฯ', 'history', 159, '2001-03-18', 'นอกจากพระมเหสีเทวีในพระเจ้าแผ่นดินแล้ว ยังมีพระสนมเจ้าจอมที่เป็นข้าบาทบริจาริกาผู้รับใช้ใกล้ชิดองค์พระมหากษัตริย์ ตั้งแต่รัชกาลที่ 1 เป็นต้นมา อีกหลายท่าน ซึ่งมีบทบาทสำคัญในราชสำนัก แต่เรื่องราวของพระสนมเจ้าจอมนั้นถูกบันทึกไว้กระจัดกระจายในจดหมายเหตุหรือบันทึกต่างๆ หนังสือเล่มนี้จึงได้รวบรวมเรื่องราวของพระสนมเจ้าจอมคนสำคัญๆ เอาไว้ ซึ่งแต่ละท่านมีเกร็ดเรื่องเล่าที่ต่างกันออกไป ซึ่งจะทำให้ชีวิตของชาววังสมัยต้นรัตนโกสินทร์เป็นต้นมา ทั้งความรัก ความทุกข์ยาก ขนมธรรมเนียม กระแสการเมือง ไปจนถึงความเปลี่ยนแปลงด้านต่างๆ ในสังคมที่มีผลจนถึงปัจจุบัน', 110, ''),
(59, 'GoldSoul', 'วิวัฒน์รัตนโกสินทร์', 'นันทเดช เมฆสวัสดิ์', 'history', 335, '1990-07-14', ' การเปลี่ยนแปลงแนวคิดของตัวบุคคลในประวัติศาสตร์ ช่วงปี พ.ศ.2475 นี้ มีให้เห็นอยู่หลายสิบคนและเป็นตัวอย่างที่ดีที่ควรศึกษา เพื่อจะได้นำมาคิดอย่างมีสติว่าประวัติศาสตร์ตรงส่วนนี้ควรจะเป็นอย่างไร ให้บทเรียนอะไรแก่สังคมไทย และให้อะไรแก่ชีวิตของเราในปัจจุบันบ้าง ซึ่งเรื่องเหล่านี้น่าจะสำคัญกว่าการพุ่งเป้าไปคิดแต่ว่า “ใครจะเป็นฝ่ายผิด ใครจะเป็นฝ่ายถูก” ในเมื่อปัจจุบันเวลาก็ผ่านมานานแล้วไม่สามารถย้อนกลับไปแก้ไขอะไรได้อีก ก็คงเหลือแต่ว่า “จะใช้เรื่องนี้เป็นบทเรียนเพื่อทำอะไรให้ประเทศไทยของเราดีขึ้นในอนาคตอย่างไร” เท่านั้นก็น่าจะเพียงพอแล้ว', 60, ''),
(60, 'GoldSoul', 'ปฏิวัติฝรั่งเศส', 'พีรวุฒิ เสนามนตรี', 'history', 247, '2002-02-12', 'การปฏิวัติฝรั่งเศสในปี 1789-1799 เป็นเหตุการณ์ที่สำคัญเหตุการณ์หนึ่งในประวัติศาสตร์มนุษยชาติ ที่แสดงให้เห็นถึงความเร่าร้อนและพลังอุดมการณ์อันแรงกล้า ในการสร้างระบบรัฐให้กับประชาชนในแผ่นดินฝรั่งเศส', 10, ''),
(61, 'GoldSoul', 'กบฏกรุงศรี', 'จิตรสิงห์ ปิยะชาติ', 'history', 190, '2000-08-10', 'ใครว่า \"อยุธยา\" ล่มเพราะพม่าเผ่าเมือง อำนาจราชบัลลังก์ต่างหากที่เป็นที่มาของความอ่อนแอ \"กบฏ\" หรือ \"การยึดอำนาจ\" ในกรุงศรีอยุทธยานั้น แน่นอนว่าย่อมมีปรากฏให้เห็นอยู่มากมายในบรรดาพงศาวดารและหลักฐานต่างๆ ที่มีอยู่ของสมัยอยุธยา กระนั้น สิ่งที่ปรากฏในหนังสือเล่มนี้ ไม่ได้เป็นเพียงเรื่องราวจากบันทึกหรือเพียงจากเอกสารชั้นต้นและชั้นรองเท่านั้น หากแต่ผู้เขียนพยายามที่นำเสนอภาพกว้างของปัญหา ซึ่งเป็นที่มาที่ไปของเรื่องราวที่เกิดขึ้น เพื่อแสดงให้ผู้อ่านได้เห็นภาพของบ้านเมือง การเมืองการปกครอง และสภาพแวดล้อมต่างๆ ของกรุงศรีอยุธยาในแต่ละยุคสมัย ซึ่งจะช่วยให้สามารถทำความเข้าใจและมองเห็นภาพของกรุงศรีอยุธยาได้อย่างกว้างและลุ่มลึกมากยิ่งกว่าที่ได้เรียนรู้หรือรับรู้มาจากตำราทั่วไป', 80, ''),
(62, 'GoldSoul', 'ภาพถ่ายคลาสสิค', 'เอนก นาวิกมูล', 'history', 289, '1999-05-16', '\"ภาพถ่ายคลาสสิค\" นับเป็นเล่มสุดท้ายของ \"ชุดมุมสะสม\" ซึ่งออกมาให้ผู้ที่ชื่นชอบสะสมภาพและเรื่องราวเก่าๆ ถึง 7 เล่มด้วยกัน เรื่องรูปถ่ายสมัยเก่านี้เมืองไทยรู้จักวิชาถ่ายรูปตั้งแต่สมัยรัชกาลที่ ๓ หรือประมาณสัก ๑๓๐-๑๔๐ ปีมาแล้ว (นับจากพ.ศ.๒๕๓๑) หากเปิดหนังสือว่าด้วยการถ่ายรูปเล่มใดก็จะต้องพบชื่อ \"หลุยส์ เจ.เอ็ม.ดาแกร์\" ชาวฝรั่งเศสทุกทีไป ในบทนี้ก็จะมีภาพประกอบบอกเล่ารายละเอียดถึงชาวฝรั่งเศสคนนี้ที่มีบทบาทกับการถ่ายภาพ \"การซื้อขายกล้องถ่ายรูปสมัยรัชกาลที่ ๕\" .. ก็มีภาพกล้องชนิดและรุ่นต่างๆ บอกลักษณะวัสดุที่ใช้ทำกล้องแต่ละรุ่น น่าสนใจมากทีเดียว \"สมุดภาพ\" .. ผู้เขียนเห็นว่าการรวมรูปเก่าๆ มาตีพพิมพ์เป็นหนังสือ เพราะเป็นห่วงว่าต่อไปรูปเก่าแก่ทั้งหลายจะค่อยๆ สูญสลายด้วยมอดแมลง ดินฟ้าอากาศ ไม่ก็ถูกขายทิ้งโยนทิ้งถังขยะ จะทำให้คนรุ่นหลังไม่ได้มีโอกาสเห็นภาพเหล่านั้น อาทิ รูปจารชนญี่ปุ่นสมัยสงครามโลกครั้งที่ ๒ รูปการรื้อกำแพงเมืองทำถนน ฯลฯ ยังมีอีกหลายเรื่องที่ผู้อ่านไม่ควรพลาดในการศึกษา', 60, ''),
(63, 'GoldSoul', '10 ตำนานสะท้านโลก', 'ดร. บัญชา ธนบุญสมบัติ', 'history', 289, '1989-12-01', 'ในโลกนี้มีตํานานเกี่ยวกับสถานที่ บุคคล หรือเหตุการณ์ต่าง ๆ นับไม่ถ้วน ซึ่งเป็นวิธีการที่คนโบราณใช้อธิบายที่มาที่ไปโดยผูกเป็นเรื่องราวขึ้นมาตามจินตนาการ ซึ่งมีหลากหลายรสชาติ เป็นเรื่องราวสุดบรรเจิด ผจญภัย สนุกสนาน ตื่นเต้น เร้าใจ เหนือเหตุผล โดยมีแก่นเรื่องธรรมะกับอธรรมและผลลัพธ์ของการกระทําที่แทรกซ่อนอยู่ แต่จะด้วยความบังเอิญหรือเพราะเป็นความเชื่อพื้นฐานของมนุษย์ก็ตามที บางเรื่องบางตํานานจึงมีเนื้อเรื่องคล้ายคลึงกัน แม้จะอยู่กันคนละวัฒนธรรม เสน่ห์ของตํานานอยู่ตรงนี้', 55, ''),
(64, 'นิดาพาอ่าน', 'น้องมาร์คเห็นคนตาย', 'ตนมองหนัง (นามแฝง)', 'nonfiction', 130, '1987-10-05', 'หนังสือ \"น้องมาร์คเห็นคนตาย\" เล่มนี้ เป็นบันทึกส่วนเสี้ยวของเหตุการณ์ทางการเมืองระหว่างและหลังเดือนเมษายน-พฤษภาคม 2553 ซึ่งผู้เขียนได้แบ่งเป็น 2 ภาค นั่นคือ ภาคแรก นำเสนอรูปแบบงานเขียนกึ่งบทภาพยนตร์ ผ่านตัวละครอย่าง \"น้องมาร์ค\" คุณจะได้เห็นลีลายียวนอันกวนโอ๊ยของ \"น้องมาร์ค\" ในการวิพากษ์วิจารณ์ทั้งเรื่องการเมือง และเสียดสีชนชั้นกลางในกรุเงทพฯ ส่วนภาคสอง บทความและบันทึกส่วนตัวของผู้เขียน ที่กล่าวถึงความหวัง ความกล้าหาญ ที่จะให้ชีวิตนั้นดำเนินเดินหน้าต่อสู่ต่อไป', 100, ''),
(65, 'นิดาพาอ่าน', 'การ์ตูนแห่งชาติชนชั้นชีวิต', 'ประเสริฐ ผลิตผลการพิมพ์', 'nonfiction\r\n', 200, '2002-04-06', 'ความรับรู้โดยทั่วไปสำหรับสื่อประเภทหนังสือการ์ตูน คือเน้นความบันเทิง และเหนือจริงเป็นหลัก แต่ในอีกมุมหนึ่งมีการ์ตูนอีกประเภท ที่สามารถนำเรื่องที่หนักหน่วงหรือเรื่องต้องห้ามอย่าง อาชญากรรม เซ็กซ์ การเมือง สงคราม ความขัดแย้งทางชนชั้นหรือเชื้อชาติ ฯลฯ มาเล่าผ่านลายเส้นทั้งในรูปแบบแอบซ่อนไปกับฉากผจญภัยแฟนตาซีอย่างกลมกลืน หรือแสดงเนื้อหาอย่างชัดเจนตรงไปตรงมา', 30, ''),
(66, 'นิดาพาอ่าน', 'ปอกเปลือกโลกร้อน', 'Peter Ward', 'nonfiction', 359, '2000-06-03', 'นำเสนอเรื่องราวการเกิดการเปลี่ยนแปลงของสภาพอากาศโลกในอดีตซึ่งส่งผลให้สิ่งมีชีวิตหลายชนิดสูญพันธ์ และนำมาเปรียบเทียบกับสถานการณ์สภาวะโลกร้อนในปัจจุบันได้อย่างน่าสนใจทีเดียว', 40, ''),
(67, 'นิดาพาอ่าน', 'ผู้มีบารมี ผู้แพ้บารมี', 'ศรีศักร วัลลิโภคม', 'nonfiction\r\n', 155, '2002-05-05', 'ช่วงเวลา 6-7 ปีที่ผ่านมา คนไทยทั่วไปมักได้ยินคำกล่าวที่คุ้นๆ ในเรื่อง \"ผู้มีบารมี\" อันเป็นผลมาจากความขัดแย้งทางการเมืองในท่ามกลางความคิดเห็นที่แตกต่างและทำให้เกิดแรงปะทะอย่างมหาศาลในสังคมไทยนี้ บทความของอาจารย์ศรีศักร วัลลิโภดม ที่เขียนให้ทัศนะที่ชัดเจน หนักแน่นมั่นคงอย่างสม่ำเสมอในทิศทางตรงกันข้ามกับบรรดานักวิชาการรุ่นใหม่ส่วนใหญ่อย่างชัดเจน การเป็นผู้มีประสบการณ์โดยสร้างความเข้าใจจากการเรียนรู้อย่างลึกซึ่งและผ่านร้อนผ่านหนาวมามากในสังคมไทย ทำให้บทความชุด \"ผู้มีบารมี ผู้แพ้บารมี\" ของอาจารย์ชุดนี้เต็มไปด้วยข้อมูลอย่างลุ่มลึกและมีเหตุผลมากกว่าข้อคิดเห็นในหลายประโยคหลายข้อความ ผู้อ่านอาจจะรู้ในสิ่งที่ควรรู้แต่ไม่เคยสนใจและอาจจะไม่ใส่ใจในรากฐานหลักการของพระมหากษัตริย์ผู้หนึ่ง ผู้ใช้ทศพิศราชธรรมที่ลึกซึ้งต่อพสกนิกรในสังคมไทยตลอดมา', 60, ''),
(68, 'นิดาพาอ่าน', 'เพื่อแผ่นดินเกิด', 'วลัยลักษณ์ ทรงศิริ', 'nonfiction', 130, '1999-07-05', 'หนังสือที่มีจุดมุ่งหมายเพื่อสร้างความเข้าใจในหลักการทางสังคมและวัฒนธรรมที่เคยเป็นเสาหลักของสังคมไทย แต่เกิดการเปลี่ยนแปลงอย่างรวดเร็วในปัจจุบัน ทำให้ผู้คนต้องเผชิญภาวะสับสนในสังคมไทยที่ยุ่งเหยิงวุ่นวาย มีความรุนแรง และไร้ซึ่งรากฐานทางชีวิตวัฒนธรรมในการดำรงชีวิต สะท้อนชีวิตวัฒนธรรมของท้องถิ่นต่างๆ ที่มีอยู่อย่างมากมาย และเคยมีธรรมาภิบาลคอยกำกับอยู่เสมอมา เพื่อให้เห็นความหลากหลายที่เรียกว่าพหุลักษณ์ทางสังคมที่เป็นรากฐานแห่งความมั่นคงในแนวคิดประชาธิปไตยแบบอุดมคติที่สังคมไทยยังคงเดินทางไปไม่ถึง', 120, ''),
(69, 'นิดาพาอ่าน', 'หรรษาอาเซียน', 'ธีรภาพ โลหิตกุล', 'nonfiction', 245, '2004-07-12', 'หรรษาอาเซียน อ่านได้เพลินๆ ชวนยิ้มหัวไปกับเรื่องราวแปลกๆ ขำๆ เรียกได้ว่าเป็นประวัติศาสตร์เกี่ยวกับวิถีผู้คน ศิลปะ ภาษา และวัฒนธรรมของชาวอาเซียนที่ถูกถ่ายเทสู่กันและกัน อีกทั้งยังจะช่วยไขข้อข้องใจในสารพันปัญหาที่หลายคนอาจติดใจสงสัย หรือไม่เคยได้ยินได้ฟังจากที่ไหนมาก่อน', 88, ''),
(70, 'นิดาพาอ่าน', 'ลับ ลวง เลือด', 'วาสนา นาน่วม', 'nonfiction', 276, '2001-11-11', 'เต็มไปด้วยข้อมูลที่ผู้คนทั้งหลายนึกไม่ถึงมากมาย ไม่ว่าจะเป็น “การเมือง” ระหว่างเสื้อแดงและกองกำลังทหารด้วยกันเอง “กองทัพปีศาจ” ที่จัดตั้งกันในแต่ละฝ่ายและห้ำหั่นกันอย่างดุเดือด สัญญาณพิเศษจาก “บุคคลสำคัญ” ที่ส่งผ่านมายังกองทัพ สมรภูมิราชประสงค์ที่กลายเป็นจุดเริ่มต้นของการ “เผาเมือง” ความตายของผู้คนทั้งฝ่ายทหารและพลเรือน แท้จริงเป็นฝีมือของใครกันแน่ การจัดตั้งโผทหารที่นำเอา “สายเหยี่ยว” ของกองทัพอำมาตย์มารวมไว้เพื่อต่อกรกับ “คนเสื้อแดง” โดยเฉพาะ\r\n\r\nหรือแม้แต่ความตายของ เสธ.แดง ผู้เขียนก็ยังสืบรู้ว่าเป็นฝีมือของ “นายสิบ” คนหนึ่ง\r\n\r\nจึงไม่อาจปฏิเสธว่า หนังสือ “ลับ ลวง เลือด” เล่มนี้ คือส่วนหนึ่งของการบันทึกประวัติศาสต์การเมืองไทยที่ทุกคนในชาติต้องจดจำ', 25, ''),
(71, 'นิดาพาอ่าน', 'ปากกาเงิน', 'ณรงค์ จันทร์เรือง', 'nonfiction', 162, '1985-06-18', 'ป็นที่น่าสังเกตว่า ในแวดวงวรรณกรรมเมื่อประมาณปี พ.ศ.2500 นักประพันธ์ในสมัยนั้นมีความตื่นตัวในการสรรค์สร้างงานเขียนเป็นอย่างมาก ขณะเดียวกัน นักเขียนอีกหลายต่อหลายคนก็ได้กระโจนเข้าสู่แวดวงที่มิใช่นักเขียน-นักหนังสือพิมพ์เพียงอย่างเดียว อีกทั้งบุคลิกของนักเขียนแต่ละคนก็อาจเหมือนหรือตรงข้ามกับเนื้อหาในบทประพันธ์ก็เป็นได้', 65, ''),
(72, 'BlackWing', 'The Ghost Of Thailand', 'สมหมาย ตามประวัติ', 'horror', 200, '1979-05-22', 'เมื่ออยากทำความรู้จักกับผีในประเทศไทยต้องหนังสือเล่มนี้ที่จะรวบรวมบรรดาสิ่งลึกลับต่างๆมากมายไว้ในเล่มเดียว', 20, ''),
(73, 'BlackWing', 'Epic Ghosts', 'Peter Dawner', 'horror', 199, '1995-11-06', 'Many Epic Ghosts in this book!\r\n- Let\'s Scared Together ', 65, ''),
(74, 'BlackWing', 'แม่นาคพระโขนง', 'อุทัย ไชยานนท์', 'horror', 95, '2000-10-10', 'หนังสือเล่มนี้จะพาคุณไปรู้จักกับแม่นาคพระโขนง ที่เชื่อกันว่าเป็นเรื่องจริงที่เกิดขึ้นในสมัยรัชกาลที่ 4 ในภายหลังได้มีการแต่งเติมเสริมต่อให้เกิดความสนุกสนานเพื่อความบันเทิง มีการนำมาสร้างเป็นภาพยนตร์หลายครั้งหลายหนแต่ละครั้ง แต่ละหน ก็ล้วนแต่เป็นที่ฮือฮาชื่นชมนิยมกันเสมอมา และโด่งดัง มาทุกยุคสมัยจนถึงปัจจุบัน   ', 150, ''),
(75, 'BlackWing', 'สุสานคนเป็น', 'กุสุมา-สินสุข ', 'horror', 195, '2000-05-09', '-', 5, ''),
(76, 'BlackWing', 'ERIC', 'Eric Carle', 'horror', 250, '2004-11-03', '-', 10, ''),
(77, 'BlackWing', 'BITE:A Vampire Handbook', 'Kevin Jackson', 'horror', 350, '1996-06-12', 'Arm yourself with garlic, stake and crucifix, for the vampires are back in force - at the top of the best-seller lists, on your TV, on the web and lurking in darkened cinemas. But, where did they come from? Why have they come back now? And how can you tell if you are one? Beginning with the first sightings of bats and blood-sucking in the Romantic period, \"Bite\" will follow the undead\'s progress through the ages, right up to the present. Alongside mini essays, anecdotes, facts and figures, each section will be punctuated with lists, such as the best places around the world for vamp tourism; rock songs with vampire allusions; box-office revenues for vamp movies; and, the top 10 Vampire clubs, video-games, vampire brides, as well as reliable and unreliable methods of killing a vampire.', 50, ''),
(78, 'BlackWing', 'PANDORA in the CONGO', 'Albert Sánchez Piñol', 'horror', 249, '2000-12-12', '-', 50, ''),
(79, 'BlackWing', 'FINAL SETTLEMENT', 'กฤติยา สุทธิชื่น', 'horror', 260, '2000-11-07', '-', 35, ''),
(80, 'StardustStyle', 'Beasts and Monsters', 'Anthony Horowitz', 'horror', 215, '1986-05-02', 'ตระกูลหมาป่าและมอนสเตอร์ที่ดุร้ายจะทำให้คุณรู้สึกหวาดกลัว โดยนักเขียนที่ค่อนข้างมีชื่อเสียง! ', 90, ''),
(81, 'StardustStyle', 'Ocean Of Blood', 'Darren Shan', 'horror', 240, '1997-07-17', 'ทำไมมหาสมุทรถึงเป็นสีเลือดกันได้ คุณจะค้นพบความน่ากลัวของแหล่งน้ำแห่งนี้ที่เต็มไปด้วยเรื่องราวที่น่าสยดสยองชวนขนหัวลุก', 49, ''),
(82, 'StardustStyle', 'House of Echoes', 'บาร์บารา เออร์สไคน์', 'horror', 360, '2000-01-05', 'การผจญภัยสุดพลิกผัน ลุ้นระทึกไปกับความผาดโผนทุกตัวอักษรด้วยพลังลึกลับแห่งหนังสือ House of Echoes มาพร้อมฮีโร่สามพี่น้องจอมเฮี้ยวผู้เปี่ยมไหวพริบ วายร้ายสุดสยองและเรื่องเหนือจริงน่าสะพรึงกลัวอีกมากมาย', 100, ''),
(83, 'StardustStyle', 'The Hunt (A Dark Torch)', 'Nan-a (Alice)', 'horror', 199, '2001-10-04', '-', 10, ''),
(84, 'StardustStyle', 'คินดะอิจิยอดนักสืบ ตอนที่ 28 โรงละครผีสิง', 'Seishi Yokomizo (เซชิ โยโคมิโซะ)', 'horror', 255, '2002-05-23', 'พบกับสุดยอดซีรีส์ลึกลับสืบสวนตลอดกาลเพื่อร่วมตอกย้ำความเหนือชั้นของปรมาจารย์ \"โยโคมิโซะ เซชิ\" ผู้สร้างนักสืบนาม \"คินดะอิจิ\" ให้เป็นตำนวนอันยิ่งใหญ่...ฤดูร้อนเืมื่อสิบเจ็ดปีก่อน \"คินดะอิจิ\" วัยหนุ่มต้องพบกับเหตุการณ์ประหลาด เมื่อสหายนักแสดงคาบูกิที่กำลังโด่งดังเกิดหายตัวไปอย่างลึกลับ ขณะกำลังแสดงฉากกลไกสำคัญในเรื่อง \"สยบมัจฉา\" ทำให้กลายเป็นปริศนาที่ฝังใจคินดะดิจิไม่ลืม', 48, ''),
(85, 'StardustStyle', 'ผีหัวขาด โดย สรจักร', 'สรจักร ศิริบริรักษ์', 'horror', 150, '2004-11-12', '\"สติขาดหาย ลมหายใจขาดห้วง ประสาทขาดสะบั้น ขวัญขาดกระจุย ๒๐ เรื่องสั้นหักมุม ที่ตีแผ่สภาวะในจิตใจลึกๆ ของมนุษย์ออกมา อย่างแจ่มชัด\"', 50, ''),
(86, 'StardustStyle', 'ผีวิทยา ghost academy', 'ดร. รอบทิศ ไวยสุศรี', 'horror', 145, '1998-08-28', ' รู้จักกับสารพัดผียอดนิยมของเมืองไทย พบประสบการณ์เจอผี ตลอดจนวิธีอุทิศกุศลแผ่เมตตาให้ไปถึงผี ถ่ายทอดโดย \"ดร.รอบทิศ ไวยสุศรี\" แฟนพันธุ์แท้พระเกจิคณาจารย์ ซึ่งได้นำเรื่องราวใน \"พระไตรปิฏก\" มาเล่าใหม่ อธิบายง่ายๆ ในลีลาการเขียนแบบชาวบ้านจับเข่าล้อมวงสนทนากัน ซึ่งทุกหัวข้อต่างก็เป็นประเด็นที่คนทั่วไปให้ความสนใจ และมักจะตั้งคำถามกันบ่อยๆ   ผีคืออะไร ตายแล้วไปไหน เจ้ากรรมนายเวรจะตามทวงแค้นเราตลอดไปหรือไม่ ผีเด็กโดนทำแท้งเฮี้ยนกว่าผีทั่วไปไหม ไหว้ผีบ้านผีเรือนทำอย่างไร จำเป็นต้องตั้งศาลไหม วิธีรับมือเมื่อผีหลอก ผีอำ สวดมนต์แบบไหน พระเครื่องอะไร ป้องกันผีได้ หนังสือเล่มนี้มีคำตอบ!', 15, ''),
(87, 'SuperStarShop', 'มหาสนุก ฉบับ 1348\r\n', 'วิธิต อุตสาหจิต', 'Comic Book', 20, '1974-05-01', 'รูปแบบและเนื้อหาของนิตยสารมหาสนุกนั้นคล้ายคลึงกับนิตยสารขายหัวเราะ กล่าวคือ เน้นการตีพิมพ์การ์ตูนแก๊กเป็นหลัก (โดยทีมงานนักเขียนการ์ตูนในนิตยสารเล่มนี้ใช้ทีมเดียวกับที่เขียนในขายหัวเราะ) เนื้อหาอาจเป็นได้ทั้งเรื่องราวในชีวิตประจำวัน เศรษฐกิจ การเมือง หรือกระแสความนิยมต่างๆ ในสังคมไทยและต่างประเทศ มีการตีพิมพ์ขำขัน ภาพตลกจากต่างประเทศ สาระน่ารู้ต่างๆ แต่ส่วนที่ต่างไปจากขายหัวเราะคือ การตีพิมพ์เรื่องสั้นในมหาสนุกนั้นจะตีพิมพ์เพียงเรื่องเดียวต่อฉบับ และมีการ์ตูนเรื่องสั้นหรือนิยายภาพชุดต่างๆ จากฝีมือของนักเขียนการ์ตูนบรรลือสาส์นลงพิมพ์ฉบับละ 2 เรื่อง ในท้ายเล่มยังมีเกมชิงรางวัลรูปแบบต่างๆ และการตอบจดหมายของผู้อ่านโดยนักเขียนการ์ตูน (ปัจจุบันได้มีการเลิกตีพิมพ์หน้าตอบจดหมายแล้ว) จากนั้นได้เพิ่มอีก 3 เกม อย่างเช่น \"คิดดีๆ มีรางวัล\" \"ตาไวๆ ได้รางวัล\" และ \"ปริศนาอักษรไขว์\"', 60, ''),
(88, 'SuperStarShop', 'มหาสนุก ฉบับ 1349\r\n', 'วิธิต อุตสาหจิต', 'Comic Book\r\n\r\n', 20, '2005-11-07', 'รูปแบบและเนื้อหาของนิตยสารมหาสนุกนั้นคล้ายคลึงกับนิตยสารขายหัวเราะ กล่าวคือ เน้นการตีพิมพ์การ์ตูนแก๊กเป็นหลัก (โดยทีมงานนักเขียนการ์ตูนในนิตยสารเล่มนี้ใช้ทีมเดียวกับที่เขียนในขายหัวเราะ) เนื้อหาอาจเป็นได้ทั้งเรื่องราวในชีวิตประจำวัน เศรษฐกิจ การเมือง หรือกระแสความนิยมต่างๆ ในสังคมไทยและต่างประเทศ มีการตีพิมพ์ขำขัน ภาพตลกจากต่างประเทศ สาระน่ารู้ต่างๆ แต่ส่วนที่ต่างไปจากขายหัวเราะคือ การตีพิมพ์เรื่องสั้นในมหาสนุกนั้นจะตีพิมพ์เพียงเรื่องเดียวต่อฉบับ และมีการ์ตูนเรื่องสั้นหรือนิยายภาพชุดต่างๆ จากฝีมือของนักเขียนการ์ตูนบรรลือสาส์นลงพิมพ์ฉบับละ 2 เรื่อง ในท้ายเล่มยังมีเกมชิงรางวัลรูปแบบต่างๆ และการตอบจดหมายของผู้อ่านโดยนักเขียนการ์ตูน (ปัจจุบันได้มีการเลิกตีพิมพ์หน้าตอบจดหมายแล้ว) จากนั้นได้เพิ่มอีก 3 เกม อย่างเช่น \"คิดดีๆ มีรางวัล\" \"ตาไวๆ ได้รางวัล\" และ \"ปริศนาอักษรไขว์\"', 200, ''),
(89, 'SuperStarShop', 'มหาสนุก ฉบับ 1350\r\n', 'วิธิต อุตสาหจิต', 'Comic Book\r\n\r\n', 20, '2005-12-07', 'รูปแบบและเนื้อหาของนิตยสารมหาสนุกนั้นคล้ายคลึงกับนิตยสารขายหัวเราะ กล่าวคือ เน้นการตีพิมพ์การ์ตูนแก๊กเป็นหลัก (โดยทีมงานนักเขียนการ์ตูนในนิตยสารเล่มนี้ใช้ทีมเดียวกับที่เขียนในขายหัวเราะ) เนื้อหาอาจเป็นได้ทั้งเรื่องราวในชีวิตประจำวัน เศรษฐกิจ การเมือง หรือกระแสความนิยมต่างๆ ในสังคมไทยและต่างประเทศ มีการตีพิมพ์ขำขัน ภาพตลกจากต่างประเทศ สาระน่ารู้ต่างๆ แต่ส่วนที่ต่างไปจากขายหัวเราะคือ การตีพิมพ์เรื่องสั้นในมหาสนุกนั้นจะตีพิมพ์เพียงเรื่องเดียวต่อฉบับ และมีการ์ตูนเรื่องสั้นหรือนิยายภาพชุดต่างๆ จากฝีมือของนักเขียนการ์ตูนบรรลือสาส์นลงพิมพ์ฉบับละ 2 เรื่อง ในท้ายเล่มยังมีเกมชิงรางวัลรูปแบบต่างๆ และการตอบจดหมายของผู้อ่านโดยนักเขียนการ์ตูน (ปัจจุบันได้มีการเลิกตีพิมพ์หน้าตอบจดหมายแล้ว) จากนั้นได้เพิ่มอีก 3 เกม อย่างเช่น \"คิดดีๆ มีรางวัล\" \"ตาไวๆ ได้รางวัล\" และ \"ปริศนาอักษรไขว์\"', 150, ''),
(90, 'SuperStarShop', 'ขายหัวเราะ ฉบับ 1472', 'เอ๋ (ศิรินันท์ วิชาตรง)', 'comic book', 20, '2005-11-10', 'นิตยสารที่นำเสนอการ์ตูนตลกสามช่องจบ หรือ การ์ตูนแก๊กเกือบตลอดทั้งเล่ม ภายในลงพิมพ์เรื่องขำขันแทรกเป็นช่วงๆ และเรื่องสั้นสามเรื่องในแต่ละฉบับ ซึ่งไอเดียในการเขียนการ์ตูนแก๊ก ขำขัน', 100, ''),
(91, 'SuperStarShop', 'ขายหัวเราะ ฉบับ 1473', 'เอ๋ (ศิรินันท์ วิชาตรง)', 'comic book', 20, '2005-12-10', 'นิตยสารที่นำเสนอการ์ตูนตลกสามช่องจบ หรือ การ์ตูนแก๊กเกือบตลอดทั้งเล่ม ภายในลงพิมพ์เรื่องขำขันแทรกเป็นช่วงๆ และเรื่องสั้นสามเรื่องในแต่ละฉบับ ซึ่งไอเดียในการเขียนการ์ตูนแก๊ก ขำขัน', 90, ''),
(92, 'SuperStarShop', 'ขายหัวเราะ ฉบับ 1474', 'เอ๋ (ศิรินันท์ วิชาตรง)', 'comic book', 20, '2006-01-12', 'นิตยสารที่นำเสนอการ์ตูนตลกสามช่องจบ หรือ การ์ตูนแก๊กเกือบตลอดทั้งเล่ม ภายในลงพิมพ์เรื่องขำขันแทรกเป็นช่วงๆ และเรื่องสั้นสามเรื่องในแต่ละฉบับ ซึ่งไอเดียในการเขียนการ์ตูนแก๊ก ขำขัน', 85, ''),
(93, 'SuperStarShop', 'ขายหัวเราะ ฉบับ 1475\r\n', 'เอ๋ (ศิรินันท์ วิชาตรง)', 'comic book', 145, '2003-03-17', 'นิตยสารที่นำเสนอการ์ตูนตลกสามช่องจบ หรือ การ์ตูนแก๊กเกือบตลอดทั้งเล่ม ภายในลงพิมพ์เรื่องขำขันแทรกเป็นช่วงๆ และเรื่องสั้นสามเรื่องในแต่ละฉบับ ซึ่งไอเดียในการเขียนการ์ตูนแก๊ก ขำขัน', 150, ''),
(94, 'SuperStarShop', 'ปังปอนด์ไอ้ตัวเล็ก ฉบับ 306\r\n', 'ภักดี แสนทวีสุข', 'Comic Book', 15, '2006-12-03', 'เด็กชายผมสามเส้น มีนิสัยซุกซน มองโลกเหมือนกับเป็นสวนสนุก มีเรื่องต้องเล่นมากมาย แต่ความขี้เล่นของเขาบางครั้งไปทำความเดือดร้อนให้คนอื่น อายุ 5 ขวบ', 120, ''),
(95, 'SuperStarShop', 'ปังปอนด์ไอ้ตัวเล็ก ฉบับ 307\r\n', 'ภักดี แสนทวีสุข', 'Comic Book', 15, '2006-12-10', 'เด็กชายผมสามเส้น มีนิสัยซุกซน มองโลกเหมือนกับเป็นสวนสนุก มีเรื่องต้องเล่นมากมาย แต่ความขี้เล่นของเขาบางครั้งไปทำความเดือดร้อนให้คนอื่น อายุ 5 ขวบ', 110, ''),
(96, 'SuperStarShop', 'ปังปอนด์ไอ้ตัวเล็ก ฉบับ 308\r\n', 'ภักดี แสนทวีสุข', 'Comic Book', 15, '2006-12-17', 'เด็กชายผมสามเส้น มีนิสัยซุกซน มองโลกเหมือนกับเป็นสวนสนุก มีเรื่องต้องเล่นมากมาย แต่ความขี้เล่นของเขาบางครั้งไปทำความเดือดร้อนให้คนอื่น อายุ 5 ขวบ', 110, ''),
(97, 'SuperStarShop', 'ปังปอนด์ไอ้ตัวเล็ก ฉบับ 309\r\n', 'ภักดี แสนทวีสุข', 'Comic Book', 15, '2006-12-24', 'เด็กชายผมสามเส้น มีนิสัยซุกซน มองโลกเหมือนกับเป็นสวนสนุก มีเรื่องต้องเล่นมากมาย แต่ความขี้เล่นของเขาบางครั้งไปทำความเดือดร้อนให้คนอื่น อายุ 5 ขวบ', 135, ''),
(98, 'Piggy', 'สาวดอกไม้กะนายกล้วยไข่ ฉบับ 288', 'เฟน สตูดิโอ', 'Comic Book', 20, '2006-04-09', '1 ใน 3 ยอดฮิตการ์ตูนสุดฮา สาวดอกไม้กะนายกล้วยไข่ที่จะมาสร้างเสียงหัวเราะให้กับทุกคน', 300, ''),
(99, 'Piggy', 'สาวดอกไม้กะนายกล้วยไข่ ฉบับ 289', 'เฟน สตูดิโอ', 'Comic Book', 20, '2006-04-16', '1 ใน 3 ยอดฮิตการ์ตูนสุดฮา สาวดอกไม้กะนายกล้วยไข่ที่จะมาสร้างเสียงหัวเราะให้กับทุกคน', 250, '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `book`
--
ALTER TABLE `book`
  ADD PRIMARY KEY (`id_ss`,`StoreName`),
  ADD KEY `StoreName` (`StoreName`) USING BTREE;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `book`
--
ALTER TABLE `book`
  ADD CONSTRAINT `book_ibfk_1` FOREIGN KEY (`id_ss`) REFERENCES `member` (`id_ss`),
  ADD CONSTRAINT `book_ibfk_2` FOREIGN KEY (`StoreName`) REFERENCES `book_store` (`StoreName`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
